name: 📖

on: [workflow_dispatch]

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: joshmgross/guestbook@main
      with:
        issue: 1
        approvers: |
          joshmgross
    - name: Update guestbook
      run: |
        if [[ `git status --porcelain` ]]; then
          git config --local user.email "actions@github.com"
          git config --local user.name "${{ github.actor }}"
          git add README.md
          git commit -m "✏ Update guestbook"
          git push
        fi
